import type { Plugin } from 'vite'

type EnvOverride =
  | Record<string, string | number | boolean | null | undefined>
  | undefined

export interface SveltekitEnvDynamicPublicOptions {
  /**
   * Values to expose on `env`, e.g.
   * { PUBLIC_BUTTON_LABEL: "Hello" }
   *
   * These are injected as a static object into the virtual module.
   */
  env?: EnvOverride
}

const sveltekitEnvDynamicPublic = (
  options?: SveltekitEnvDynamicPublicOptions,
): Plugin => {
  const { env } = options ?? {}

  /**
   * This plugin captures imports of the "$env/dynamic/public" module and
   * replaces them with a virtual module that exports an `env` object.
   *
   * This is a workaround for Storybook's lack of support for SvelteKit's
   * dynamic env imports.
   */
  const moduleId = '$env/dynamic/public'
  const virtualModuleId = 'virtual:env/dynamic/public'

  /**
   * > Internally, plugins that use virtual modules should prefix the module ID
   * > with \0 while resolving the id, a convention from the rollup ecosystem.
   *
   * - https://vite.dev/guide/api-plugin#virtual-modules-convention
   */
  const resolvedVirtualModuleId = `\0${virtualModuleId}`

  // Build a safe JS source string for the virtual module.
  // JSON.stringify drops undefined; we also preserve primitive types.
  const envObjectLiteral = env ? JSON.stringify(env) : '{}'

  return {
    name: 'vite-plugin-sveltekit-env-dynamic-public',
    enforce: 'pre',

    resolveId(id) {
      if (id === moduleId) {
        return resolvedVirtualModuleId
      }
    },

    load(id) {
      if (id === resolvedVirtualModuleId) {
        return `
          // Generated by vite-plugin-sveltekit-env-dynamic-public
          export const env = ${envObjectLiteral};
        `
      }
    },
  }
}

export { sveltekitEnvDynamicPublic }
export default sveltekitEnvDynamicPublic
